var i = require('./js/initapp')
i.app.get('/getclientpicbyclientid/:id',(req,res)=>{
    i.executor.getClientPicByClientId(req,res)
})
i.app.post('/insertsuspect',(req,res)=>{
    i.executor.insertSuspect(req,res)
})
i.app.post('/updateclient',(req,res)=>{
    i.executor.updateClient(req,res)
})
i.app.post('/proposesurvey',(req,res)=>{
    i.executor.proposeSurvey(req,res)
})
i.app.post('/proposeinstall',(req,res)=>{
    i.executor.proposeInstall(req,res)
})
i.app.post('/createinstallreport',(req,res)=>{
    i.executor.createInstallReport(req,res)
})
i.app.post('/createsurveyreport',(req,res)=>{
    i.executor.createSurveyReport(req,res)
})
i.app.listen(process.env.PORT||i.appSetting.port)
